### ISSUE TITLE
Run flake8 on notebook code

### ISSUE THREAD

**Issue by hodgestar** [qutip/qutip-tutorials#13]
I had another idea -- we can add a CI check that converts the notebooks to Python scripts (using Jupytext) and then runs flake8 on those scripts.

**Comment by hodgestar** [comment]
nbQA look great -- let's try it.

I will put in a vote against using a pre-build action. This should be a few lines (hopefully) in the CI config and obscuring those behind a pre-built action doesn't seem worth it.

**Comment by christian512** [comment]
The check with `flake8` was added in https://github.com/qutip/qutip-tutorials/pull/22. Therefore I close this issue.
