### ISSUE TITLE
Make the tutorial index more beautiful

### ISSUE THREAD

**Issue by hodgestar** [qutip/qutip-tutorials#16]
It would be awesome to make the tutorial index more pretty and user friendly so that we can link to it directly from the qutip.org website. Some ideas for things to include:

- Links to Nbviewer (for viewing the notebook as-is with output)
- A links to MyBinder (with an environment.yml file, for trying the notebooks out)
- Some headings (maybe this can be derived from folder names initially, or something?)
- Some CSS styling that matches the qutip.org site somewhat.

**Comment by christian512** [comment]
This issue was closed with https://github.com/qutip/qutip-tutorials/pull/40.
