### ISSUE TITLE
Treat exceptions raised outside of notebook cells as errors

### ISSUE THREAD

**Issue by hodgestar** [qutip/qutip-tutorials#33]
I opened a feature request on the nbmake repository to handle this case https://github.com/treebeardtech/nbmake/issues/77.

**Comment by hodgestar** [comment]
This has been fixed in nbmake 1.3.4 -- https://github.com/treebeardtech/nbmake/issues/77. We should try it out and then close this once we've confirmed it works for us.

**Comment by christian512** [comment]
I can confirm that the error which we had before in one of the notebooks is now detected correctly by `nbmake`. I upgraded the version of `nbmake` in #39  and close this issue accordingly.
