### ISSUE TITLE
Fix failure to display circuits when building notebooks in CI

### ISSUE THREAD

**Issue by hodgestar** [qutip/qutip-tutorials#47]
See failures in run https://github.com/qutip/qutip-tutorials/actions/runs/3123223660/jobs/5065718100

**Comment by BoxiLi** [comment]
This looks hard to debug. The error message looks like something went wrong with ImageMagick. This error didn't show in the PR. Does it mean that something changed during the last month?

**Comment by hodgestar** [comment]
Maybe the PR didn't run these tests? Not sure.

**Comment by hodgestar** [comment]
It looks like circuit generation is working fine now, so closing this.
