### ISSUE TITLE
Port "Steady-State: Homodyned Jaynes-Cummings emission" tutorial to QuTiP 5.

### ISSUE THREAD

**Issue by hodgestar** [qutip/qutip-tutorials#91]
The [Homodyned Jaynes-Cummings emission tutorial](https://github.com/qutip/qutip-tutorials/blob/main/tutorials-v4/time-evolution/020_homodyned-Jaynes-Cummings-emission.md) is currently only available for QuTiP 4. It needs to be ported to QuTiP 5.

Steps:

- Copy the Markdown notebook into the appropriate folder under  `tutorials-v5`.
- Update the notebook to work with QuTiP 5.
- Make any small improvements needed to the notebook.
- Add some assertions to the end of the notebook to ensure it ran correctly (e.g. check some results).
- Check that the notebook is included in the website build scripts.

**Comment by alan-nala** [comment]
Hi, I would like to work on this issue for the UnitaryHack.

**Comment by GustavoPetronilo** [comment]
I would like to work in this issue. It is still open?

**Comment by hodgestar** [comment]
@ArturDomingues I accepted and merged your PR (#98). Could you comment on this issue so that I can assign it to you? Then the UnitaryHACK administrators will be able to see that you claimed it.

@alan-nala @GustavoPetronilo Thank you for your submissions. Artur's PR was completed first.

**Comment by ArturDomingues** [comment]
Ok, what do I need to do with respect to UnitaryHACK?

**Comment by hodgestar** [comment]
> Ok, what do I need to do with respect to UnitaryHACK?

Thanks for commenting. That allowed me to assign the completed issue to you and now the UnitaryHACK team will do the rest. All done from our side, I believe.

**Comment by ArturDomingues** [comment]
Nice, I hope I can help solve more things in the near future. Especially in the main qutip repo. I have used it a lot in my masters it is one of the nicest tools out there for simulating problems.

**Comment by hodgestar** [comment]
Looking forward to seeing your PRs to QuTiP and great to hear it was helpful during your MSc. There are likely still many small improvements to make in QuTiP 5 and many bigger projects to pursue.
