### ISSUE TITLE
 Port "Steady-State: Optomechanical System in the Single-Photon Strong-Coupling Regime" tutorial to QuTiP 5.

### ISSUE THREAD

**Issue by hodgestar** [qutip/qutip-tutorials#92]
The [Steady-State: Optomechanical System](https://github.com/qutip/qutip-tutorials/blob/main/tutorials-v4/time-evolution/019_optomechanical-steadystate.md) tutorial is currently only available for QuTiP 4. It needs to be ported to QuTiP 5.

Steps:

- Copy the Markdown notebook into the appropriate folder under tutorials-v5.
- Update the notebook to work with QuTiP 5.
- Make any small improvements needed to the notebook.
- Add some assertions to the end of the notebook to ensure it ran correctly (e.g. check some results).
- Check that the notebook is included in the website build scripts.

**Comment by obliviateandsurrender** [comment]
I would like to take this!

**Comment by hodgestar** [comment]
Congratulations @obliviateandsurrender and thank you for contributing to QuTiP.

I've assigned this issue to you. The UnitaryHACK team should do the rest.
