### ISSUE TITLE
Port "Steady-State: Time-dependent (periodic) quantum system" tutorial to QuTiP 5.

### ISSUE THREAD

**Issue by hodgestar** [qutip/qutip-tutorials#93]
The [Steady-State: Time-dependent (periodic) quantum system](https://github.com/qutip/qutip-tutorials/blob/main/tutorials-v4/time-evolution/021_quasi-steadystate-driven-system.md) tutorial is currently only available for QuTiP 4. It needs to be ported to QuTiP 5.

Steps:

- Copy the Markdown notebook into the appropriate folder under tutorials-v5.
- Update the notebook to work with QuTiP 5.
- Make any small improvements needed to the notebook.
- Add some assertions to the end of the notebook to ensure it ran correctly (e.g. check some results).
- Check that the notebook is included in the website build scripts.

**Comment by Davide9710** [comment]
Hi @hodgestar, I opened a PR for this issue, and I realized it has already been solved... @marcogobbo thank you and nice work!

**Comment by hodgestar** [comment]
@marcogobbo Thanks again for adding the explanations to the ported tutorial and congratulations on sucessfully participating in UnitaryHACK. I've assigned the completed issue to you and the UnitaryHACK team should do the rest.
